name: Build & Deploy CDN (fast)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: cdn-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (if lockfile present)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund
          fi

      # Wenn deine Name-JSONs bereits im Repo sind:
      - name: Build dex only
        run: npm run build:dex

      - name: Show dex files
        run: |
          if [ -d public/cards/dex ]; then
            echo "Dex in public/"
            ls -lah public/cards/dex | head -60
          elif [ -d cards/dex ]; then
            echo "Dex in cards/"
            ls -lah cards/dex | head -60
          else
            echo "ERROR: Kein dex/ Ordner gefunden" && exit 1
          fi

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
