name: Cards Daily (names + dex)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: cards-daily
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240   # <— vorher 60, jetzt 4h

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20 (with cache if lockfile)
        if: hashFiles('package-lock.json','npm-shrinkwrap.json','yarn.lock') != ''
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Node 20 (no cache)
        if: hashFiles('package-lock.json','npm-shrinkwrap.json','yarn.lock') == ''
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund || true
          fi

      - name: Build names + dex
        env:
          POKEMONTCG_API_KEY: ${{ secrets.POKEMONTCG_API_KEY }}
        run: npm run build

      - name: Commit & push changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh cards + dex ($(date -u +'%Y-%m-%d'))"
          git pull --rebase origin main || true
          git push --force-with-lease origin HEAD:main
