name: Cards Daily (names + dex)

on:
  schedule:
    - cron: "0 3 * * *"   # täglich 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: cards-daily
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies (if lockfile present)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm i --no-audit --no-fund
          fi

      # Baut Namen und DEX (npm run build -> build:names + build:dex)
      - name: Build names + dex
        env:
          POKEMONTCG_API_KEY: ${{ secrets.POKEMONTCG_API_KEY }}
        run: npm run build

      - name: Sanity check (dex files)
        run: |
          ls -lah public/cards/dex 2>/dev/null | head -60 || true
          ls -lah cards/dex         2>/dev/null | head -60 || true

      - name: Configure Git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & push changes (if any)
        run: |
          set -e
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git add -A
          git commit -m "chore: refresh cards + dex ($(date -u +'%Y-%m-%d'))"
          git pull --rebase origin main || true
          git push --force-with-lease origin HEAD:main

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
