name: Prices Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "15 2 * * *" # täglich 02:15 UTC (nach Cards-Run)

jobs:
  prices:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        env:
          CI: true

      - name: Build price time-series
        env:
          # Optional:
          PRICECHARTING_API_KEY: ${{ secrets.PRICECHARTING_API_KEY }}
          PRICECHARTING_ENDPOINT: ${{ secrets.PRICECHARTING_ENDPOINT }}
        run: node scripts/fetch-prices.mjs

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/prices
          git commit -m "chore: refresh price series ($(date -u +%F))" || echo "no changes"
          git push
