name: Prices Daily

on:
  workflow_dispatch:
  schedule:
    # täglich 02:15 UTC (nach Cards-Run)
    - cron: "15 2 * * *"

permissions:
  contents: write

concurrency:
  group: prices-daily
  cancel-in-progress: false

jobs:
  build-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Keine Abhängigkeiten nötig – direkt das Skript starten
      - name: Build price time-series
        env:
          PRICECHARTING_API_KEY: ${{ secrets.PRICECHARTING_API_KEY }}   # optional
          PRICECHARTING_ENDPOINT: ${{ secrets.PRICECHARTING_ENDPOINT }} # optional (Proxy)
        run: node scripts/fetch-prices.mjs

      - name: Commit & Push (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/prices
          if git diff --cached --quiet; then
            echo "No price changes to commit."
          else
            git commit -m "chore: refresh price series ($(date -u +%F))"
            git push
          fi
