name: Update Cards (daily)

on:
  schedule:
    - cron: "0 3 * * *"    # täglich 03:00 UTC
  workflow_dispatch:        # manuell startbar

permissions:
  contents: write

jobs:
  build-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # wichtig für rebase
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Pre-pull (make sure we're up-to-date)
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Run builder
        env:
          POKEMONTCG_API_KEY: ${{ secrets.POKEMONTCG_API_KEY }}
        run: |
          npm run update

      - name: Configure Git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: refresh cards ($(date -u +'%Y-%m-%d'))"

      - name: Rebase onto latest main (just in case)
        run: |
          git fetch origin main
          git pull --rebase origin main || true

      - name: Push
        run: |
          git push origin HEAD:main
